ALTER TABLE GRUPO 
ADD CONSTRAINT GRUPO_CURSO_FK FOREIGN KEY (curso_id)
REFERENCES CURSO(codigo);

ALTER TABLE GRUPO 
ADD CONSTRAINT GRUPO_PROFESOR_FK FOREIGN KEY (profesor_id)
REFERENCES PROFESOR(cedula);
------------------------------------------

ALTER TABLE NOTICIA
ADD CONSTRAINT NOTICIA_GRUPO_FK FOREIGN KEY(grupo_id)
REFERENCES GRUPO(grupo_id);
-------------------------------------------------
ALTER TABLE CARPETA
ADD CONSTRAINT CARPETA_GRUPO_FK FOREIGN KEY(grupo_id)
REFERENCES GRUPO(grupo_id);

ALTER TABLE ARCHIVO
ADD CONSTRAINT ARCHIVO_CARPETA_FK FOREIGN KEY(carpeta_id)
REFERENCES CARPETA(carpeta_id);
--------------------------------------------------------
ALTER TABLE RUBROS
ADD CONSTRAINT RUBROS_GRUPO_FK FOREIGN KEY(grupo_id)
REFERENCES GRUPO(grupo_id);

ALTER TABLE EVALUACION
ADD	CONSTRAINT EVALUACION_RUBROS_FK FOREIGN KEY(rubro_id)
REFERENCES RUBROS(rubro_id);

ALTER TABLE ENTREGABLE
ADD CONSTRAINT ENTREGABLE_EVALUACION_FK FOREIGN KEY(evaluacion_id)
REFERENCES EVALUACION(evaluacion_id);
------------------------------------------------------
ALTER TABLE SUB_GRUPO
ADD CONSTRAINT SUB_GRUPO_ESTUDIANTE_FK FOREIGN KEY(estudiante_id)
REFERENCES ESTUDIANTE(carnet);

ALTER TABLE SUB_GRUPO
ADD CONSTRAINT SUB_GRUPO_A_GRUPO_FK FOREIGN KEY(grupo_id)
REFERENCES GRUPO(grupo_id);

ALTER TABLE SUB_GRUPO
ADD CONSTRAINT SUB_GRUPO_ENTREGABLE_FK FOREIGN KEY(entregable_id)
REFERENCES ENTREGABLE(entregable_id);
--------------------------------------------------

ALTER TABLE ESTUDIANTE_GRUPO
ADD CONSTRAINT ESTUDIANTE_GRUPO_A_ESTUDIANTE_FK FOREIGN KEY(estudiante_id)
REFERENCES ESTUDIANTE(carnet);

ALTER TABLE ESTUDIANTE_GRUPO
ADD CONSTRAINT ESTUDIANTE_GRUPO_A_GRUPO_FK FOREIGN KEY(grupo_id)
REFERENCES GRUPO(grupo_id);
--------------------------------------------------------------

ALTER TABLE ESTUDIANTE_CURSO
ADD CONSTRAINT ESTUDIANTE_CURSO_A_ESTUDIANTE_FK FOREIGN KEY(estudiante_id)
REFERENCES ESTUDIANTE(carnet);

ALTER TABLE ESTUDIANTE_CURSO
ADD CONSTRAINT ESTUDIANTE_CURSO_A_CURSO_FK FOREIGN KEY(curso_id)
REFERENCES CURSO(codigo);
--------------------------------------------------------------

ALTER TABLE PROFESOR_CURSO
ADD CONSTRAINT PROFESOR_CURSO_A_PROFESOR_FK FOREIGN KEY(profesor_id)
REFERENCES PROFESOR(cedula);

ALTER TABLE PROFESOR_CURSO
ADD CONSTRAINT PROFESOR_CURSO_A_CURSO_FK FOREIGN KEY(curso_id)
REFERENCES CURSO(codigo);